[package]
name = "vmm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0.26", features = ["fs", "ioctl", "feature"] }
thiserror = "1"
kvm-ioctls = "0"
elfloader = "0.16"
log = "0.4"
env_logger = "0.10"
x86_64 = "0"

[build-dependencies]
bindgen = "0.63"
